### ISSUE TITLE
Setup subdomains

### ISSUE THREAD

**Issue by grant** [dubhacks/dubhacks.github.io#55]
Setup

14f.dubhacks.co
15s.dubhacks.co

**Comment by grant** [comment]
@karan Can you setup the subdomains?

i.e. `14f.dubhacks.co => dubhacks.co/14f/`

**Comment by karan** [comment]
Let's not keep every site as a subdirectory. That just shouts 'issues'.  dubhacks.github.io should be empty. that repo will redirect to whatever the latest site is. then repo's like "f14" will have their corresponding sites.

The DNS will be happy and the subdomains will work the way they should. No nasty redirects.

**Comment by grant** [comment]
See https://github.com/dubhacks/15s/issues/1
